site_name: Prompt2Sign
theme:
  name: material

nav:
    - Home: index.md
    - Quick Start: quickStart.md
    - Download Data:
        - All links: download/downloadData.md
        - ASL Part: download/ASL.md
        - GSL Part: download/GSL.md
        - DSGS Part: download/DSGS.md
        - LSF-CH Part: download/LSF-CH.md
        - LIS-CH Part: download/LIS-CH.md
        - LSA Part: download/LSA.md
        - KSL Part: download/KSL.md
        - TSL Part: download/TSL.md
    - Tool Usage:
        - All links: tool4data/tools_list.md
        - Clean Tool: tool4data/cleanTool.md
        - 2D to 3D: tool4data/2Dto3D.md
        - Prompt Tool: tool4data/promptTool.md
    - FAQ: FAQ.md
    - How To Cite: howtoCite.md
    - Contact Us: contactUs.md
    - Acknowledgements: acknowledgements.md

extra_css:
  - stylesheets/extra.css